// Package oidc authenticates users against a single OpenID Connect provider
// using the Authorization Code flow with PKCE (S256). Endpoints are resolved
// via OIDC discovery from the issuer URL; the ID token is validated against
// the provider's published signing keys. Login-time gating (allowed domains,
// allowed users, allowed groups, verified email) and admin-group mapping are
// applied here so handlers only ever see a normalized, authorized Identity.
package oidc

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"slices"
	"strings"
	"sync"
	"time"

	"golang.org/x/oauth2"

	gooidc "github.com/coreos/go-oidc/v3/oidc"
)

// requestTimeout bounds every HTTP call to the provider (discovery, JWKS,
// token exchange).
const requestTimeout = 10 * time.Second

// Default claim names, overridable via Config.
const (
	defaultUsernameClaim = "preferred_username"
	defaultEmailClaim    = "email"
	defaultGroupsClaim   = "groups"
)

// ErrNotAuthorized means the user authenticated at the provider but failed a
// gating rule (domain, user, group, or verified-email). Distinguished from
// protocol errors so callers can report "forbidden" instead of "login failed".
var ErrNotAuthorized = errors.New("oidc: identity not authorized")

// Config holds OIDC relying-party settings.
type Config struct {
	IssuerURL    string
	ClientID     string
	ClientSecret string
	RedirectURL  string
	Scopes       []string // Extra scopes beyond openid/profile/email (e.g. "groups").

	UsernameClaim string // Claim for the local username (default "preferred_username").
	EmailClaim    string // Claim for the email address (default "email").
	GroupsClaim   string // Claim holding group memberships (default "groups").

	AllowedDomains []string // Allow logins whose email domain matches (OR'd with AllowedUsers).
	AllowedUsers   []string // Allow logins whose email matches exactly (OR'd with AllowedDomains).
	AllowedGroups  []string // When set, require membership in at least one of these groups.
	AdminGroups    []string // Membership in any of these groups grants is_admin.

	// EmailVerifiedRequired rejects logins whose email_verified claim is not
	// true. Applies whenever an email claim is present, and always for
	// AllowedDomains/AllowedUsers matching.
	EmailVerifiedRequired bool
}

// Identity is the normalized result of a successful, authorized OIDC login.
// Issuer+Subject is the stable unique key; the other fields are profile data
// refreshed on every login.
type Identity struct {
	Issuer   string
	Subject  string
	Username string
	Email    string
	IsAdmin  bool
}

// LoginState carries the per-login secrets generated by BeginLogin that the
// caller must stash (e.g. in a signed cookie) and hand back to CompleteLogin.
type LoginState struct {
	State    string `json:"state"`
	Nonce    string `json:"nonce"`
	Verifier string `json:"verifier"` // PKCE code verifier.
}

// Provider is an OIDC relying party bound to one issuer. Discovery is lazy:
// the first login attempt fetches the provider metadata, so taillight starts
// (and stays up) even when the IdP is unreachable at boot.
// Safe for concurrent use.
type Provider struct {
	cfg    Config
	logger *slog.Logger
	client *http.Client

	mu       sync.Mutex
	oauthCfg *oauth2.Config
	verifier *gooidc.IDTokenVerifier
}

// New creates a Provider. No network calls are made until the first login.
func New(cfg Config, logger *slog.Logger) *Provider {
	if cfg.UsernameClaim == "" {
		cfg.UsernameClaim = defaultUsernameClaim
	}
	if cfg.EmailClaim == "" {
		cfg.EmailClaim = defaultEmailClaim
	}
	if cfg.GroupsClaim == "" {
		cfg.GroupsClaim = defaultGroupsClaim
	}
	return &Provider{
		cfg:    cfg,
		logger: logger,
		client: &http.Client{Timeout: requestTimeout},
	}
}

// ensure performs OIDC discovery once and caches the resulting endpoints and
// ID-token verifier. Discovery deliberately uses a background context: go-oidc
// retains it for later JWKS refreshes, so a request-scoped context would break
// key rotation after the first request ends. Each HTTP call is still bounded
// by the client timeout.
func (p *Provider) ensure() (*oauth2.Config, *gooidc.IDTokenVerifier, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.oauthCfg != nil {
		return p.oauthCfg, p.verifier, nil
	}

	ctx := gooidc.ClientContext(context.Background(), p.client)
	provider, err := gooidc.NewProvider(ctx, p.cfg.IssuerURL)
	if err != nil {
		return nil, nil, fmt.Errorf("oidc discovery for %s: %w", p.cfg.IssuerURL, err)
	}

	scopes := []string{gooidc.ScopeOpenID, "profile", "email"}
	for _, s := range p.cfg.Scopes {
		if !slices.Contains(scopes, s) {
			scopes = append(scopes, s)
		}
	}

	p.oauthCfg = &oauth2.Config{
		ClientID:     p.cfg.ClientID,
		ClientSecret: p.cfg.ClientSecret,
		RedirectURL:  p.cfg.RedirectURL,
		Endpoint:     provider.Endpoint(),
		Scopes:       scopes,
	}
	p.verifier = provider.Verifier(&gooidc.Config{ClientID: p.cfg.ClientID})
	p.logger.Info("oidc discovery complete", "issuer", p.cfg.IssuerURL)
	return p.oauthCfg, p.verifier, nil
}

// BeginLogin generates the per-login state/nonce/PKCE-verifier secrets and
// returns the provider authorization URL to redirect the browser to.
func (p *Provider) BeginLogin() (authURL string, ls LoginState, err error) {
	oauthCfg, _, err := p.ensure()
	if err != nil {
		return "", LoginState{}, err
	}

	state, err := randomToken()
	if err != nil {
		return "", LoginState{}, err
	}
	nonce, err := randomToken()
	if err != nil {
		return "", LoginState{}, err
	}
	ls = LoginState{State: state, Nonce: nonce, Verifier: oauth2.GenerateVerifier()}

	authURL = oauthCfg.AuthCodeURL(ls.State,
		gooidc.Nonce(ls.Nonce),
		oauth2.S256ChallengeOption(ls.Verifier),
	)
	return authURL, ls, nil
}

// CompleteLogin exchanges the callback authorization code, validates the ID
// token (signature via JWKS, issuer, audience, expiry, nonce), and applies
// the gating rules. Returns ErrNotAuthorized (wrapped) when the user
// authenticated but is not allowed in; any other error is a protocol failure.
func (p *Provider) CompleteLogin(ctx context.Context, code string, ls LoginState) (*Identity, error) {
	oauthCfg, verifier, err := p.ensure()
	if err != nil {
		return nil, err
	}
	ctx = gooidc.ClientContext(ctx, p.client)

	token, err := oauthCfg.Exchange(ctx, code, oauth2.VerifierOption(ls.Verifier))
	if err != nil {
		return nil, fmt.Errorf("oidc token exchange: %w", err)
	}

	rawIDToken, ok := token.Extra("id_token").(string)
	if !ok || rawIDToken == "" {
		return nil, errors.New("oidc token response missing id_token")
	}

	idToken, err := verifier.Verify(ctx, rawIDToken)
	if err != nil {
		return nil, fmt.Errorf("oidc id_token validation: %w", err)
	}
	if idToken.Nonce != ls.Nonce {
		return nil, errors.New("oidc id_token nonce mismatch")
	}

	var claims map[string]any
	if err := idToken.Claims(&claims); err != nil {
		return nil, fmt.Errorf("oidc id_token claims: %w", err)
	}

	ident := p.resolveIdentity(idToken.Issuer, idToken.Subject, claims)
	if err := p.authorize(ident, emailVerified(claims), stringSlice(claims[p.cfg.GroupsClaim])); err != nil {
		return nil, err
	}
	return ident, nil
}

// resolveIdentity maps validated ID-token claims to an Identity. Username
// falls back from the configured claim to the email local-part to the raw
// subject, and is lowercased to match the case-insensitive users table.
func (p *Provider) resolveIdentity(issuer, subject string, claims map[string]any) *Identity {
	email, _ := claims[p.cfg.EmailClaim].(string)
	email = strings.TrimSpace(email)

	username, _ := claims[p.cfg.UsernameClaim].(string)
	username = strings.TrimSpace(username)
	if username == "" && email != "" {
		username, _, _ = strings.Cut(email, "@")
	}
	if username == "" {
		username = subject
	}

	groups := stringSlice(claims[p.cfg.GroupsClaim])
	isAdmin := false
	for _, g := range groups {
		if containsFold(p.cfg.AdminGroups, g) {
			isAdmin = true
			break
		}
	}

	return &Identity{
		Issuer:   issuer,
		Subject:  subject,
		Username: strings.ToLower(username),
		Email:    email,
		IsAdmin:  isAdmin,
	}
}

// authorize applies the gating rules to an authenticated identity.
func (p *Provider) authorize(ident *Identity, verified bool, groups []string) error {
	// A present-but-unverified email is rejected outright: unverified claims
	// must not pass domain gating or end up as trusted profile data.
	if p.cfg.EmailVerifiedRequired && ident.Email != "" && !verified {
		return fmt.Errorf("%w: email not verified", ErrNotAuthorized)
	}

	if len(p.cfg.AllowedDomains) > 0 || len(p.cfg.AllowedUsers) > 0 {
		if ident.Email == "" {
			return fmt.Errorf("%w: no email claim for domain/user gating", ErrNotAuthorized)
		}
		_, domain, _ := strings.Cut(ident.Email, "@")
		if !containsFold(p.cfg.AllowedDomains, domain) && !containsFold(p.cfg.AllowedUsers, ident.Email) {
			return fmt.Errorf("%w: email not in allowed domains or users", ErrNotAuthorized)
		}
	}

	if len(p.cfg.AllowedGroups) > 0 {
		allowed := false
		for _, g := range groups {
			if containsFold(p.cfg.AllowedGroups, g) {
				allowed = true
				break
			}
		}
		if !allowed {
			return fmt.Errorf("%w: not a member of any allowed group", ErrNotAuthorized)
		}
	}

	return nil
}

// emailVerified reads the email_verified claim, tolerating providers that
// encode it as a string instead of a bool. Absent counts as unverified.
func emailVerified(claims map[string]any) bool {
	switch v := claims["email_verified"].(type) {
	case bool:
		return v
	case string:
		return strings.EqualFold(v, "true")
	default:
		return false
	}
}

// stringSlice converts a JSON claim value ([]any of strings) to []string.
func stringSlice(v any) []string {
	items, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func containsFold(list []string, s string) bool {
	for _, item := range list {
		if strings.EqualFold(item, s) {
			return true
		}
	}
	return false
}

// randomToken returns a 32-byte cryptographically random base64url string.
func randomToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate random token: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
